dist: xenial   # required for Python >= 3.7
language: python
cache: pip

python:
    - "3.5"
    - "3.6"
    - "3.7"

# install jupyter and get reveal.js as we will need it to build the website
# from Travis
install:
    - pip install jupyter
    - wget https://github.com/hakimel/reveal.js/archive/master.zip
    - unzip master.zip
    - mv reveal.js-master reveal.js
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - jupyter nbconvert demo-ecas-ophidia/ecas-b2share-tn.ipynb --to slides --reveal-prefix=reveal.js
    - python setup.py test
    - sphinx-build -b html docs/ docs/_build/html/

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    git checkout --orphan gh-pages
    git rm -rf --cached .
    mv demo-ecas-ophidia/ecas-b2share-tn.slides.html demo-ecas-ophidia/index.html
    git add -f --ignore-errors demo-ecas-ophidia/index.html reveal.js
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi
