channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
- nodejs=11
- nbconvert=5.5
- widgetsnbextension=3.5
- ipykernel=5.1
- ipywidgets=7.5
- ipyleaflet=0.11.1
- altair=3.1
- bqplot=0.11.6
- dask=2.1
- matplotlib=3.1
- pandas=0.24
- python=3.7
- seaborn=0.9
- sympy=1.4
- pyyaml
- traittypes==0.2.1
- xarray
- geoviews
- jupyterlab=1.0
- dask=2.1
- matplotlib=3.1
- pandas=0.24
- pip:
  - ecasb2share==0.0.1b16
